#!/bin/bash

if [[ $UID != 0 ]]; then
  echo "root required. Did you forget sudo?"
  echo "sudo $0 $*"
  exit 1
fi

JAILS=(sshd nginx-http-auth)

for jail in ${JAILS[@]}; do
  fail2ban-client status $jail
done

