#!/bin/bash
# Download a .gitignore from github.com/github/gitignore project
#
# Presents a curated list of project types I'm likely to use and once selected
# downloads the approriate .gitignore

LANGUAGES=( None Node VisualStudio Ruby Sass Rust C C++ Go Java )

select language in "${LANGUAGES[@]}"; do

	if [ "$language" != "None" ]; then
		url="https://raw.githubusercontent.com/github/gitignore/master/$language.gitignore"
		echo "$url -> .gitignore"
		wget --quiet --output-document .gitignore $url
	fi

	break
done

