#!/bin/bash

DEFAULT_EMAIL="burkemd1+github@gmail.com"

git-ignore

git init

echo -n "Email? ($DEFAULT_EMAIL): "
read email

if [ "$email" == "" ]; then
	email=$DEFAULT_EMAIL
fi

git config --local user.email "$email"
