#!/bin/bash

git branch --merged |\
   grep --invert-match "\*" |\
   grep --invert-match master |\
   grep --invert-match dev |\
   xargs --max-args=1 --no-run-if-empty git branch --delete

git remote prune origin
