#!/bin/bash

DEFAULT_EMAIL="burkemd1+github@gmail.com"

LANGUAGES=( C C++ Node VisualStudio Ruby Rust Go Java Sass None )

select language in "${LANGUAGES[@]}"; do

	if [ "$language" != "None" ]; then
		url="https://raw.githubusercontent.com/github/gitignore/master/$language.gitignore"
		echo "$url -> .gitignore"
		wget --quiet --output-document .gitignore $url
	fi

	break
done

exit 1

git init

echo -n "Email? ($DEFAULT_EMAIL): "
read email

if [ "$email" == "" ]; then
	email=$DEFAULT_EMAIL
fi

git config --local user.email "$email"
