#!/bin/bash
# Turns the argument file into a symlink to a file in the bin-scripts repo

install_dir=`dirname $(realpath $0)`
script_name=$(basename $1)
installed_script="$install_dir/$script_name"

echo "Linking $HOME/bin/$script_name -> $install_dir/$script_name"
mv $HOME/bin/$script_name $install_dir/$script_name
ln -s $install_dir/$script_name $HOME/bin/$script_name


