#!/bin/bash

# mkrepo - Creates a repo on the ssh server in the $HOME/repos/ directory

user_host=$1
repo_name=$2

if [ "$user_host" == "" ]; then
	echo "user@host required"
	exit 1
fi

if [ "$repo_name" == "" ]; then
	repo_name=$(basename "$PWD")
fi

ssh $user_host "mkdir -p ~/repos/$repo_name.git && cd ~/repos/$repo_name.git && git init --bare ."
