#!/usr/bin/ruby

require 'rubygems'
require 'yaml'

config = YAML.load(File.read("config/database.yml"))
database= config[ENV["RAILS_ENV"] || "development"]

unless database["adapter"] =~ /mysql/
	puts "Current RAILS_ENV is not a mysql database"
	exit 1
end

cmd = "mysql -h\"#{database['host']}\" -u\"#{database['username']}\" -p\"#{database['password']}\" -P\"#{database['port']}\" -D\"#{database['database']}\""
puts cmd
exec cmd
